import { NextResponse } from "next/server";
import { Task } from "@/types/task";

const today = new Date();
const todayStr = today.toISOString().split("T")[0];
const tomorrowStr = new Date(today.getTime() + 86400000).toISOString().split("T")[0];
const day3Str = new Date(today.getTime() + 86400000 * 2).toISOString().split("T")[0];
const day5Str = new Date(today.getTime() + 86400000 * 4).toISOString().split("T")[0];

const mockTasks: Task[] = [
  {
    id: "1",
    user_id: "mock",
    title: "Sună la doctor",
    deadline: new Date().toISOString(),
    priority: "high",
    category: "Sănătate",
    status: "pending",
    raw_input: "Trebuie să sun la doctor mâine",
    created_at: new Date().toISOString(),
    scheduled_date: todayStr,
    scheduled_start: `${todayStr}T09:00:00`,
    scheduled_end: `${todayStr}T09:30:00`,
  },
  {
    id: "2",
    user_id: "mock",
    title: "Cumpără pâine",
    deadline: new Date(today.getTime() + 86400000 * 2).toISOString(),
    priority: "low",
    category: "Cumpărături",
    status: "pending",
    raw_input: "Cumpără pâine până vineri",
    created_at: new Date().toISOString(),
    scheduled_date: tomorrowStr,
    scheduled_start: `${tomorrowStr}T18:00:00`,
    scheduled_end: `${tomorrowStr}T18:30:00`,
  },
  {
    id: "3",
    user_id: "mock",
    title: "Trimite raportul",
    deadline: new Date(today.getTime() + 86400000 * 5).toISOString(),
    priority: "medium",
    category: "Muncă",
    status: "done",
    raw_input: "Trimite raportul până lunea viitoare",
    created_at: new Date().toISOString(),
    scheduled_date: null,
    scheduled_start: null,
    scheduled_end: null,
  },
  {
    id: "4",
    user_id: "mock",
    title: "Review PR-uri",
    deadline: new Date(today.getTime() + 86400000).toISOString(),
    priority: "high",
    category: "Muncă",
    status: "pending",
    raw_input: "Review la PR-uri mâine dimineață",
    created_at: new Date().toISOString(),
    scheduled_date: todayStr,
    scheduled_start: `${todayStr}T10:00:00`,
    scheduled_end: `${todayStr}T11:00:00`,
  },
  {
    id: "5",
    user_id: "mock",
    title: "Sedintă echipă",
    deadline: new Date(today.getTime() + 86400000 * 3).toISOString(),
    priority: "medium",
    category: "Muncă",
    status: "pending",
    raw_input: "Sedintă de echipă joi la 14",
    created_at: new Date().toISOString(),
    scheduled_date: day3Str,
    scheduled_start: `${day3Str}T14:00:00`,
    scheduled_end: `${day3Str}T15:00:00`,
  },
  {
    id: "6",
    user_id: "mock",
    title: "Pregătire prezentare",
    deadline: new Date(today.getTime() + 86400000 * 4).toISOString(),
    priority: "high",
    category: "Muncă",
    status: "pending",
    raw_input: "Pregătește prezentarea pentru vineri",
    created_at: new Date().toISOString(),
    scheduled_date: day5Str,
    scheduled_start: `${day5Str}T09:00:00`,
    scheduled_end: `${day5Str}T12:00:00`,
  },
  {
    id: "7",
    user_id: "mock",
    title: "Alergat în parc",
    deadline: null,
    priority: "low",
    category: "Sănătate",
    status: "pending",
    raw_input: "Alergat în parc",
    created_at: new Date().toISOString(),
    scheduled_date: null,
    scheduled_start: null,
    scheduled_end: null,
  },
  {
    id: "8",
    user_id: "mock",
    title: "Rezervă restaurant",
    deadline: new Date(today.getTime() + 86400000).toISOString(),
    priority: "medium",
    category: "Personal",
    status: "pending",
    raw_input: "Rezervă restaurant pentru vineri seară",
    created_at: new Date().toISOString(),
    scheduled_date: null,
    scheduled_start: null,
    scheduled_end: null,
  },
];

export async function GET() {
  return NextResponse.json({ tasks: mockTasks });
}
